name: SentinelOne CNS Scan

on: 
  pull_request:
    paths: 
    - 'AWS-examples\**'

jobs:
  s1-cns-cli:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1cnscli:latest
      options: --entrypoint ""

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure SentinelOne CNS CLI
        run: s1-cns-cli config --api-token $TOKEN --endpoint-url https://app.pingsafe.com
        env:
         TOKEN: ${{secrets.SENTINELONE_CNS_TOKEN}}

      - name: Configure git config
        run: git config --global --add safe.directory $PWD

      - name: Run Secret Detector
        run:  s1-cns-cli scan secret -d $PWD --pull-request origin/$SRC $DEST
        env:
          DEST: ${{ github.event.pull_request.base.sha }}
          SRC: ${{ github.event.pull_request.head.ref }}
